#!/usr/bin/env python3
"""J.A.R.V.I.S. — CLI entry point.

Usage:
    python main.py doctor              # environment capability report
    python main.py demo                # full offline perceive->reason->act cycle
    python main.py scrape <url>        # parser-only extraction
    python main.py browse <url>        # selenium session against a URL
    python main.py gui-test            # pyautogui smoke test (desktop only)
    python main.py word [path]         # MS Word cycle (report blueprint)
    python main.py powerpoint [path]   # MS PowerPoint cycle (briefing blueprint)
    python main.py excel [path]        # MS Excel cycle (power budget blueprint)
    python main.py office-demo         # Word -> PowerPoint -> Excel, one by one
    python main.py run <skill> --url X # run a registered skill
"""

from __future__ import annotations

import argparse
import json
import os
import sys

from jarvis import JarvisAgent, __version__
from jarvis.config import Settings
from jarvis.fixtures import FixtureServer
from jarvis.logging_setup import get_logger
from jarvis.skills.office import ExcelSkill, PowerPointSkill, WordSkill
from jarvis.skills.recon import WebReconSkill

log = get_logger("jarvis.cli")


# ── MS Office demo blueprints (used by the office CLI missions) ──────────────
WORD_BLUEPRINT = {
    "title": "J.A.R.V.I.S. Systems Report",
    "paragraphs": [
        "This report is generated by the J.A.R.V.I.S. automation agent to "
        "demonstrate native Microsoft Word document control.",
        "The agent perceived the document, reasoned about the mission, acted "
        "through the word engine, and verified the artifact end to end.",
    ],
    "table": [
        ["Pillar", "Engine", "Status"],
        ["GUI Manipulation", "PyAutoGUI", "READY"],
        ["Data Ingestion", "requests + bs4", "READY"],
        ["Browser Automation", "Selenium", "READY"],
        ["Office Automation", "python-docx / openpyxl / python-pptx", "READY"],
    ],
}

POWERPOINT_BLUEPRINT = {
    "slides": [
        {"title": "J.A.R.V.I.S. Status Briefing",
         "bullets": ["Modular Python automation agent",
                     "State-machine driven mission lifecycle",
                     "Office automation: Word, PowerPoint, Excel"],
         "notes": "Opening slide — generated by the PowerPoint engine."},
        {"title": "Active Capabilities",
         "bullets": ["GUI manipulation via PyAutoGUI",
                     "Data ingestion via requests + BeautifulSoup",
                     "Dynamic browser automation via Selenium",
                     "MS Office document engines (this deck)"],
         "notes": "Walk the five pillars."},
        {"title": "Roadmap",
         "bullets": ["Voice I/O front-end",
                     "Skill scheduler + mission memory",
                     "Vision-guided GUI plans"],
         "notes": "Close with what comes next."},
    ],
}

EXCEL_BLUEPRINT = {
    "title": "J.A.R.V.I.S. Power Budget",
    "sheet": "Power Budget",
    "headers": ["Subsystem", "Draw (W)", "Hours", "Energy (Wh)"],
    "rows": [
        ["Reactor core", 3100, 24, None],
        ["Sensor array", 220, 24, None],
        ["Actuation bus", 480, 6, None],
        ["Cognition cluster", 950, 24, None],
    ],
    "formulas": {
        "D2": "=B2*C2", "D3": "=B3*C3", "D4": "=B4*C4", "D5": "=B5*C5",
    },
    "format": {"target": "A1:D1", "bold": True, "fill": "FF2060",
               "col_width": 18},
}


# ── commands ─────────────────────────────────────────────────────────────────
def cmd_doctor(_args: argparse.Namespace) -> int:
    settings = Settings.load()
    agent = JarvisAgent(settings)
    from jarvis.cognition.llm import LLMBrain

    print(f"\n  J.A.R.V.I.S. {__version__} — capability report\n  " + "─" * 46)
    for name, module in agent.modules.items():
        mark = "✓" if module.capability.available else "✗"
        mode = "dry-run shadow" if module.dry_run else "live"
        print(f"  [{mark}] {name:<8} {module.capability.detail}  -> mode: {mode}")
    brain = "configured" if settings.llm_api_key else "not configured (OfflineBrain fallback)"
    print(f"  [{'✓' if settings.llm_api_key else '!'}] brain    "
          f"{settings.llm_model} @ {settings.llm_base_url} -> {brain}")
    if isinstance(agent.brain, LLMBrain):
        pass
    print()
    return 0


def _print_result(result) -> None:
    print("\n  " + "═" * 60)
    print(f"  RESULT: {'SUCCESS' if result.success else 'FAILURE'}"
          f"  ({result.attempts} attempt(s), {result.elapsed_s}s)")
    print(f"  brain      : {result.brain}")
    if result.rationale:
        print(f"  rationale  : {result.rationale}")
    print(f"  verify     : {result.summary}")
    print("  actions:")
    for a in result.actions_executed:
        flag = " (dry-run)" if a.get("dry_run") else ""
        print(f"    • {a['tool']}.{a['action']}{flag}")
    if result.errors:
        print("  errors:")
        for e in result.errors:
            print(f"    ! {e}")
    print("\n  state trace:")
    for line in result.state_trace:
        print(f"    {line}")
    print()


def cmd_demo(args: argparse.Namespace) -> int:
    """Full state-machine cycle against the bundled fixture site (offline-safe)."""
    settings = Settings.load()
    with FixtureServer() as server, \
         JarvisAgent(settings, dry_run=args.dry_run) as agent:
        target = server.page("control_panel.html")
        print(f"\n  J.A.R.V.I.S. demo — target: {target}\n")

        agent.register(WebReconSkill(url=target))
        result = agent.run("web_recon")
        _print_result(result)
        return 0 if result.success else 1


def cmd_scrape(args: argparse.Namespace) -> int:
    settings = Settings.load()
    agent = JarvisAgent(settings, dry_run=args.dry_run).boot()
    parser = agent.modules["parser"]
    res = parser.get(args.url)
    payload = {
        "url": res.url,
        "status": res.status_code,
        "title": parser.title(res.soup),
        "headings": parser.headings(res.soup),
        "links": parser.find_links(res.soup, base_url=args.url)[:20],
        "tables": parser.find_tables(res.soup)[:3],
        "forms": parser.find_forms(res.soup),
    }
    print(json.dumps(payload, indent=2, ensure_ascii=False))
    agent.shutdown()
    return 0 if res.ok else 2


def cmd_browse(args: argparse.Namespace) -> int:
    settings = Settings.load()
    agent = JarvisAgent(settings, dry_run=args.dry_run).boot()
    browser = agent.modules["browser"]
    try:
        info = browser.open(args.url)
        print(json.dumps({"opened": info, "cookies": 0 if browser.dry_run
                          else len(browser._d().get_cookies())}, indent=2))
        shot = browser.screenshot()
        print(json.dumps(shot, indent=2))
        code = 0
    finally:
        agent.shutdown()
    return code


def cmd_gui_test(args: argparse.Namespace) -> int:
    agent = JarvisAgent(Settings.load(), dry_run=args.dry_run).boot()
    gui = agent.modules["gui"]
    print(json.dumps({
        "capability": str(gui.capability),
        "screen": gui.size(),
        "cursor": gui.position(),
    }, indent=2))
    agent.shutdown()
    return 0


# ── MS Office cycles (Word / PowerPoint / Excel) ────────────────────────────
def _run_office(skill, label: str, args: argparse.Namespace) -> int:
    settings = Settings.load()
    with JarvisAgent(settings, dry_run=args.dry_run) as agent:
        print(f"\n  J.A.R.V.I.S. MS {label} cycle — target: {skill.path}\n")
        agent.register(skill)
        result = agent.run(skill.name)
        _print_result(result)
        return 0 if result.success else 1


def cmd_word(args: argparse.Namespace) -> int:
    settings = Settings.load()
    path = args.path or os.path.join(settings.office_output_dir,
                                     "jarvis_report.docx")
    return _run_office(WordSkill(path=path, blueprint=WORD_BLUEPRINT),
                       "Word", args)


def cmd_powerpoint(args: argparse.Namespace) -> int:
    settings = Settings.load()
    path = args.path or os.path.join(settings.office_output_dir,
                                     "jarvis_briefing.pptx")
    return _run_office(PowerPointSkill(path=path,
                                       blueprint=POWERPOINT_BLUEPRINT),
                       "PowerPoint", args)


def cmd_excel(args: argparse.Namespace) -> int:
    settings = Settings.load()
    path = args.path or os.path.join(settings.office_output_dir,
                                     "jarvis_power_budget.xlsx")
    return _run_office(ExcelSkill(path=path, blueprint=EXCEL_BLUEPRINT),
                       "Excel", args)


def cmd_office_demo(args: argparse.Namespace) -> int:
    """Run the three MS Office missions one by one in a single agent session."""
    settings = Settings.load()
    out = settings.office_output_dir
    missions = [
        ("MS Word", WordSkill(
            path=os.path.join(out, "jarvis_report.docx"),
            blueprint=WORD_BLUEPRINT)),
        ("MS PowerPoint", PowerPointSkill(
            path=os.path.join(out, "jarvis_briefing.pptx"),
            blueprint=POWERPOINT_BLUEPRINT)),
        ("MS Excel", ExcelSkill(
            path=os.path.join(out, "jarvis_power_budget.xlsx"),
            blueprint=EXCEL_BLUEPRINT)),
    ]
    print("\n  J.A.R.V.I.S. MS Office demo — Word -> PowerPoint -> Excel\n")
    failed = 0
    with JarvisAgent(settings, dry_run=args.dry_run) as agent:
        for label, skill in missions:
            print("  " + "─" * 60)
            print(f"  mission: {label} — target: {skill.path}")
            agent.register(skill)
            result = agent.run(skill.name)
            _print_result(result)
            if not result.success:
                failed += 1
    print(f"  office demo complete: {len(missions) - failed}/{len(missions)}"
          " mission(s) SUCCESS\n")
    return 0 if failed == 0 else 1


# ── wiring ───────────────────────────────────────────────────────────────────
def build_parser() -> argparse.ArgumentParser:
    p = argparse.ArgumentParser(prog="jarvis",
                                description="J.A.R.V.I.S. automation agent")
    p.add_argument("--dry-run", action="store_true", default=None,
                   help="force dry-run shadow mode (default: auto per-module)")
    p.add_argument("--log-level", default=None)
    sub = p.add_subparsers(dest="cmd", required=True)

    sub.add_parser("doctor", help="probe environment capabilities").set_defaults(fn=cmd_doctor)
    sub.add_parser("demo", help="full offline agent cycle (state machine)").set_defaults(fn=cmd_demo)

    s = sub.add_parser("scrape", help="parse a URL with requests+bs4")
    s.add_argument("url")
    s.set_defaults(fn=cmd_scrape)

    b = sub.add_parser("browse", help="open a URL with selenium")
    b.add_argument("url")
    b.set_defaults(fn=cmd_browse)

    sub.add_parser("gui-test", help="pyautogui smoke test").set_defaults(fn=cmd_gui_test)

    w = sub.add_parser("word", help="MS Word cycle (report blueprint -> .docx)")
    w.add_argument("path", nargs="?", default=None,
                   help="target .docx (default: <office dir>/jarvis_report.docx)")
    w.set_defaults(fn=cmd_word)

    pp = sub.add_parser("powerpoint",
                        help="MS PowerPoint cycle (briefing blueprint -> .pptx)")
    pp.add_argument("path", nargs="?", default=None,
                    help="target .pptx (default: <office dir>/jarvis_briefing.pptx)")
    pp.set_defaults(fn=cmd_powerpoint)

    xl = sub.add_parser("excel", help="MS Excel cycle (power budget -> .xlsx)")
    xl.add_argument("path", nargs="?", default=None,
                    help="target .xlsx (default: <office dir>/jarvis_power_budget.xlsx)")
    xl.set_defaults(fn=cmd_excel)

    sub.add_parser("office-demo",
                   help="run the Word -> PowerPoint -> Excel missions one by one"
                   ).set_defaults(fn=cmd_office_demo)
    return p


def main(argv: list[str] | None = None) -> int:
    # keep unicode JSON pretty on C-locale pipes
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")
    args = build_parser().parse_args(argv)
    if args.log_level:
        import os
        os.environ["JARVIS_LOG_LEVEL"] = args.log_level
    try:
        return args.fn(args)
    except KeyboardInterrupt:
        print("\n[jarvis] interrupted — FAILSAFE respected")
        return 130


if __name__ == "__main__":
    sys.exit(main())
